### ISSUE TITLE
Module tawkto not found at line 50 in file classes/controller/ModuleAdminController.php

### ISSUE THREAD

**Issue by aravindb2002** [tawk/tawk-prestashop#1]
Hi ,

I am using prestashop version 1.6.1.0 and when try to configure the module , i am getting below error. Pease suggest

Module tawkto not found
at line 50 in file classes/controller/ModuleAdminController.php
1.         if (!$tab->module)
2.             throw new PrestaShopException('Admin tab '.get_class($this).' is not a module tab');
3. 
4.         $this->module = Module::getInstanceByName($tab->module);
5.         if (!$this->module->id)
6.             throw new PrestaShopException("Module {$tab->module} not found");
7.     }
8. 
9.     /**
10.      \* Creates a template object
11.      *
    ModuleAdminControllerCore->__construct - [line 31 - modules/tawkto/controllers/admin/AdminTawktoController.php]
    AdminTawktoController->__construct - [line 131 - classes/controller/Controller.php] - [2 Arguments]
    ControllerCore::getController - [line 366 - classes/Dispatcher.php] - [1 Arguments]
    DispatcherCore->dispatch - [line 54 - admin/index.php]

**Comment by tawk-devj** [comment]
Hello,

Do you still see the issue on your end?
If yes, please refer and update to the latest version of the module.

Thank you.
