### ISSUE TITLE
Prestashop 1.6.1.18

### ISSUE THREAD

**Issue by centoasa** [tawk/tawk-prestashop#10]
To make the plugin work correctly, the row must be==>
$this->ps_versions_compliancy = array('min' => '1.5', 'max' => '1.6.1.18');
The plugin works correctly in version 1.6.1.18, but the customer data pre-washed by prestashop are not displayed, like its name or surname.
They are only displayed if the customer writes them in the pre-chat form
It would instead be very useful to be able to view customer data from prestashop

**Comment by GeekOfAges** [comment]
Multiple installation issues have been fixed in newer versions.
Closing this as stale
