### ISSUE TITLE
I can't download or open attachments from the users 

### ISSUE THREAD

**Issue by kate8945** [tawk/tawk-prestashop#11]
Screenshots or docs from useres with non-english titles aren't available for me. 
I can't download it or open. 
There is always a link like that: https://tawk.link/5acf3938d7591465c7096f3b/vc/5b10e503ba7dc7f617300631/v/3184c04bc045cd4e86c7d737f4a5fb4eed173280/%D0%AD%D0%A6%D0%9F.png 
Support chat operator told me that the only way to solve the problem was to ask users to rename the docs or screenshot, using english letters.

**Comment by GeekOfAges** [comment]
Closing this since file downloads are dashboard/widget issue, not integration issue.
If you are still experiencing the issue - our support team is always available via live chat 24x7.
