### ISSUE TITLE
Prestashop 1.7.6.2 - login and password dissapear after few hours

### ISSUE THREAD

**Issue by dominiaz** [tawk/tawk-prestashop#14]
In Prestashop module works fine for a few hours. Then I need to put my login and password again in the module.
Please help me :)

**Comment by alvinjohnsonso** [comment]
Hi! I know it's almost a year but just wanted to inform you that I just tested this earlier and I didn't encounter this issue.

Tested on Prestashop 1.6.1.24, 1.7.6.9, and 1.7.7.0
