### ISSUE TITLE
Strange message on footer

### ISSUE THREAD

**Issue by centoasa** [tawk/tawk-prestashop#2]
as you can see in my screenshot:
https://www.evernote.com/shard/s272/sh/7302972d-9756-44ef-8243-ac85c4752e2a/450cb6f878fcd8d75ec042946147b2c5
on footer appear this strange message
Thank you

**Comment by Uebix** [comment]
This is related to an error in tpl files together the use of cloudflare that protect emails in html.
You can find the fix here:
https://github.com/tawk/tawk-prestashop/pull/3

**Comment by tawk-devj** [comment]
Hello,

Do you still see the issue on your end?
If yes,please refer to the latest version of the module.

Thank you.
