### ISSUE TITLE
Non-static method Tawkto::getPropertyAndWidget() should not be called statically

### ISSUE THREAD

**Issue by therampagerado** [tawk/tawk-prestashop#30]
![image](https://github.com/tawk/tawk-prestashop/assets/11251370/c5a591af-90ef-497c-805a-c37d5cb569f8)

and

![image](https://github.com/tawk/tawk-prestashop/assets/11251370/b3a6a51c-6d27-44cd-8a44-27fd7ebb3378)

**Comment by eug-L** [comment]
hi @therampagerado thanks for reporting this, we are able to fix this, but may I know how do you get this message to show?
