### ISSUE TITLE
Tawk support for Prestashop 8.x

### ISSUE THREAD

**Issue by TheEnglishGartner** [tawk/tawk-prestashop#31]
Hi,

Is there a etc for releasing the supported version for Prestashop 8.x?

**Comment by cantalupo555** [comment]
I need it too.

**Comment by ZaDarkSide** [comment]
You can use my fork https://github.com/ZaDarkSide/tawk-prestashop/releases/tag/1.2.3 until the PR https://github.com/tawk/tawk-prestashop/pull/33 is merged or an official version is released.

Hope it helps!

**Comment by MasterChips1** [comment]
Hi,

I tested your fork, but since our PS is still version 8.0.5, I couldn't use it :(

**Comment by ZaDarkSide** [comment]
> Hi,
> 
> I tested your fork, but since our PS is still version 8.0.5, I couldn't use it :(

Well what was the problem then? Do you have an error or something?

**Comment by TheEnglishGartner** [comment]
Hi it is wokring fine for me on Prestashop 8.1.2 although I get a warning in the module 

![No name ](https://github.com/tawk/tawk-prestashop/assets/92990704/dd931ef3-1342-4287-bff0-0d18b83a7ebe)

**Comment by ZaDarkSide** [comment]
> Hi it is wokring fine for me on Prestashop 8.1.2 although I get a warning in the module

I can't see any warning in the screenshot provided...what are you trying to show in the screenshot?

**Comment by TheEnglishGartner** [comment]
![No name ](https://github.com/tawk/tawk-prestashop/assets/92990704/fe981ec7-410c-4837-8acf-95409902051f)

It does not clearly says what the warning is. It just says one warning and then the module Tawk. Advarsel = Warning - as indicated in the screenshot best

**Comment by TheEnglishGartner** [comment]
Hi again - Perfect it disappeared - Also I have connected to Tawk, and it works like a charm. 

THank you very much. If you need me to test something just share your thoughts 

Should I close the ticket it as of now?

**Comment by ZaDarkSide** [comment]
It's best to leave the issue open so that an official answer is made about this, I only provided a temporary solution until there is an official update about this.

**Comment by TheEnglishGartner** [comment]
ok I have reopened it Thank you very much

**Comment by ZaDarkSide** [comment]
> ok I have reopened it Thank you very much

No problem, I had the same issue when trying to install the official module that PrestaShop 8.x is not supported and decided I should try add support for 8.x myself, so after I did manage to solve it for myself then I just shared the solution so maybe it helps other people until it's fixed in the official version of the module.

Hopefully we will see an official solution soon.

**Comment by TheEnglishGartner** [comment]
Hi @ZaDarkSide 

I have just upgraded to PS 8.1.6 and now the module can't be installed - have you come across this?

![Skærmbillede 2024-05-25 053524](https://github.com/tawk/tawk-prestashop/assets/92990704/b56dddbb-8d4b-423f-ad1c-15e5c6e31dfa)

best,

**Comment by ZaDarkSide** [comment]
@TheEnglishGartner I will try and see what changed and adjust to the changes so that it works again.

**Comment by TheEnglishGartner** [comment]
@ZaDarkSide Thank you looking forward to the outcome

**Comment by TheEnglishGartner** [comment]
Hi @ZaDarkSide  I just wanted to let you know,. that it is the version check of your module towards PS which is fialing according to installation

**Comment by TheEnglishGartner** [comment]
Hi I changed the tawk.php file in relation to the below:

 public function __construct()
    {
        $this->name = 'tawkto';
        $this->tab = 'front_office_features';
        $this->version = '1.2.3';
        $this->author = 'tawk.to';
        $this->need_instance = 0;
        $this->ps_versions_compliancy = array('min' => '1.5', 'max' => '8.1.3');

To:

 public function __construct()
    {
        $this->name = 'tawkto';
        $this->tab = 'front_office_features';
        $this->version = '1.2.3';
        $this->author = 'tawk.to';
        $this->need_instance = 0;
        $this->ps_versions_compliancy = array('min' => '1.5', 'max' => '8.1.6');

I have it installed and it is working. I do hope you will update it into your repository as the the package belongs to you - I do hope you are ok with me updating the file. 

Best,

**Comment by ZaDarkSide** [comment]
> Hi I changed the tawk.php file in relation to the below:
> 
> public function __construct() { $this->name = 'tawkto'; $this->tab = 'front_office_features'; $this->version = '1.2.3'; $this->author = 'tawk.to'; $this->need_instance = 0; $this->ps_versions_compliancy = array('min' => '1.5', 'max' => '8.1.3');
> 
> To:
> 
> public function __construct() { $this->name = 'tawkto'; $this->tab = 'front_office_features'; $this->version = '1.2.3'; $this->author = 'tawk.to'; $this->need_instance = 0; $this->ps_versions_compliancy = array('min' => '1.5', 'max' => '8.1.6');
> 
> I have it installed and it is working. I do hope you will update it into your repository as the the package belongs to you - I do hope you are ok with me updating the file.
> 
> Best,

I haven't had the time to check the issue out, but I will update it.

**Comment by ZaDarkSide** [comment]
I have updated the release here https://github.com/ZaDarkSide/tawk-prestashop/releases/tag/1.2.3b

**Comment by Fashdey** [comment]
@ZaDarkSide - You are a hero! <3

The one you just provided is out-of-date since they made a hotfix release
8.1.6 -> 8.1.7
I changed that myself in the latest version you have provided which worked perfect

**Comment by Fashdey** [comment]
I don't know if you have done so already, but I have just reached out to one on their Chat "Matt" which said he forwarded the request of updating the official widget

I provided links to this thread as well as @ZaDarkSide 's PR https://github.com/tawk/tawk-prestashop/pull/33

Can't tell if that was just a standard answer from their part, but now we have a record in this "Issue" that we have tried reaching out

**Comment by eug-L** [comment]
Hi everyone, support for Prestashop 8 has just been released, please download the latest module version 1.4.0 [here](https://github.com/tawk/tawk-prestashop/releases/download/1.4.0/tawk-prestashop-8.x-1.4.0.zip) or on the releases page.

Many thanks to @ZaDarkSide for helping set up the initial code and getting it to work!
