### ISSUE TITLE
Tawk Module installation problems with PrestaShop v.1.7.8.8

### ISSUE THREAD

**Issue by sebastian-marinescu** [tawk/tawk-prestashop#32]
Hi, 

I had some issues in the shop, so I've checked and saw we were still von v.1.1
So I've downloaded the latest version v1.2.3 and tried to install it, which threw an error, and PrestaShop automatically disabled it.

I re-activated it, and now I can enter the settings. So _at the end_ everything was ok. 

Still wanted to let you know, as it is unexpected behavior... 

Best regards, 
and thanks for this great service!

**Comment by eug-L** [comment]
Hi @sebastian-marinescu thanks for opening this issue, we have since fixed a bug in the upgrade script that was causing this in #33
