### ISSUE TITLE
Not working for 1.7.1.x

### ISSUE THREAD

**Issue by ssuchanowski** [tawk/tawk-prestashop#4]
Hey,

Is this still supported? Are you planning to update it?

**Comment by tawk-devj** [comment]
Hi ssuchanowski,

Thank you for contacting us. Yes prestashop 1.7.1.x is still supported, and updates for the latest version are incoming...

**Comment by tuhingr** [comment]
I tried with presta 1.7.2.0 but not working with github module

**Comment by ssuchanowski** [comment]
Yeah, no, I am not able to install it. Tried latest release from here.

**Comment by tawk-devj** [comment]
Hi,

Apologies for the delayed response. 
We will post updates to the module this week for prestashop 1.7.2.

**Comment by lauromolina** [comment]
Hi, 

 Great to read! are the changes ready for prestashop1.7.2 ?

**Comment by santiagobrito** [comment]
Not working for PS 1.7.2.1 :(

**Comment by tawk-devj** [comment]
Hello,

Apologies for the late update.
The module files have been updated now to work with Prestashop version 1.7.x.

**Comment by jimix974** [comment]
hello, Anyone could use it on prestashop 1.7.4 please?

thanks a lot

**Comment by centoasa** [comment]
Installation is impossible on 1.7.5.2

**Comment by GeekOfAges** [comment]
If installation issues persist for latest version of plugin, please open new ticket or contact our support team live chat 24x7.
