### ISSUE TITLE
Uncaught Error: Class 'Controllermoduletawkto' not found 

### ISSUE THREAD

**Issue by mubasshir** [tawk/tawk-prestashop#5]
Complete Error:
```
Fatal error: Uncaught Error: Class 'Controllermoduletawkto' not found in /project-folder/system/storage/modification/system/engine/loader.php on line 39

Error: Class 'Controllermoduletawkto' not found in /project-folder/system/storage/modification/system/engine/loader.php on line 39
```

Prestashop version: 2.1.0.1
Plugin downloaded from: [PrestaShop Market](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31763&filter_member=tawkto)

**Comment by eug-L** [comment]
Hi I think you may be referring to Opencart 2 tawk.to module, if this issue is still persisting, please open an issue in our Opencart 2 [repository](https://github.com/tawk/tawk-opencart2/issues), thank you
