### ISSUE TITLE
Tawk.to addon is not displaying

### ISSUE THREAD

**Issue by DJIronic** [tawk/tawk-prestashop#6]
Hello,

I have problem with adding Tawk chat into prestashop (1.6). I installed the plugin without any problem, then I logged into my account and I selected the right widget. But nothing on the main page...even when I open source code by browser, I can't find anything with word "tawk".

Then I realized that newly bought plugin for pop up banners is not working too...CSS and JS files are loaded, no error in browser console. But no popup banner and tawk chat on the homepade. 

Yes, I cleared + turned off CloudFlate and Presta cache and I tried another PC and browser.

Website is [here](https://olimpex.eu).

Any ideas? Thank you for your time guys.

**Comment by JhonniimV** [comment]
Hola, me ocurre, igual, en prestashop 1.7.1.1, no me aparece nada del widget de tawk,to. Gracias.

**Comment by eug-L** [comment]
This should be fixed, please install our latest version, thanks
